# Generated by Django 5.0.1 on 2024-06-15 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentclass",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="teacherclass",
            name="classes",
            field=models.ManyToManyField(to="classes.class"),
        ),
        migrations.AddField(
            model_name="teacherclass",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
    ]
