# Generated by Django 5.0.6 on 2024-07-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherclass',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('standard', 'division')},
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
        migrations.DeleteModel(
            name='TeacherClass',
        ),
        migrations.RemoveField(
            model_name='class',
            name='note',
        ),
    ]
