# Generated by Django 5.0.6 on 2024-07-07 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_teacherclass_classes_and_more'),
        ('schools', '0002_alter_school_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'standard', 'division')},
        ),
    ]
