# Generated by Django 5.0.6 on 2024-07-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_options_alter_class_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('standard', 'division')},
        ),
        migrations.RemoveField(
            model_name='class',
            name='school',
        ),
    ]
