# Generated by Django 5.0.1 on 2024-06-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("school_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=255)),
                ("established_date", models.DateField()),
                ("principal", models.CharField(max_length=50)),
                (
                    "vice_principal",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("website", models.URLField(blank=True, max_length=100, null=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
