# Generated by Django 5.0.1 on 2024-06-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="email",
            field=models.EmailField(default="foo@bar.com", max_length=255),
            preserve_default=False,
        ),
    ]
