# Generated by Django 5.0.1 on 2024-06-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={
                "ordering": ["name"],
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
            },
        ),
        migrations.RemoveField(
            model_name="school",
            name="principal",
        ),
        migrations.RemoveField(
            model_name="school",
            name="vice_principal",
        ),
        migrations.AddField(
            model_name="school",
            name="principal_name",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="school",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
