# Generated by Django 5.0.1 on 2024-06-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("student", "Student"), ("teacher", "Teacher")],
                        max_length=7,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_code",
                    models.CharField(
                        choices=[
                            ("read_announcement", "Read Announcement"),
                            ("read_write_announcement", "Read, Write Announcement"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StudentDetail",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        limit_choices_to={"type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("admission_date", models.DateField()),
                ("father_contact", models.CharField(max_length=15)),
                ("mother_contact", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="TeacherDetail",
            fields=[
                (
                    "teacher",
                    models.OneToOneField(
                        limit_choices_to={"type": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                    ),
                ),
                ("qualifications", models.TextField()),
                ("hire_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("math", "Mathematics"),
                            ("science", "Science"),
                            ("english", "English"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"type": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.ManyToManyField(blank=True, to="users.userpermission"),
        ),
    ]
