# Generated by Django 5.0.1 on 2024-06-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentdetail",
            options={
                "verbose_name": "Student Detail",
                "verbose_name_plural": "Student Details",
            },
        ),
        migrations.AlterModelOptions(
            name="teacherdetail",
            options={
                "verbose_name": "Teacher Detail",
                "verbose_name_plural": "Teacher Details",
            },
        ),
        migrations.AlterModelOptions(
            name="teachersubject",
            options={
                "verbose_name": "Teacher Subject",
                "verbose_name_plural": "Teacher Subjects",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelOptions(
            name="userpermission",
            options={
                "verbose_name": "User Permission",
                "verbose_name_plural": "User Permissions",
            },
        ),
        migrations.RemoveField(
            model_name="teachersubject",
            name="teacher",
        ),
        migrations.AddField(
            model_name="teacherdetail",
            name="subjects",
            field=models.ManyToManyField(blank=True, to="users.teachersubject"),
        ),
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                choices=[
                    ("+1", "United States/Canada"),
                    ("+91", "India"),
                    ("+44", "United Kingdom"),
                ],
                default=None,
                max_length=4,
            ),
            preserve_default=False,
        ),
    ]
