# Generated by Django 5.0.1 on 2024-06-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_middle_name_alter_usercontact_relation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercontact",
            options={
                "verbose_name": "User Contact",
                "verbose_name_plural": "User Contacts",
            },
        ),
        migrations.AlterField(
            model_name="usercontact",
            name="relation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("guardian", "Guardian"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
