# Generated by Django 5.0.6 on 2024-07-07 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_teacherclass_classes_and_more'),
        ('users', '0003_alter_usercontact_options_alter_usercontact_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class'),
        ),
        migrations.AddField(
            model_name='teacherdetail',
            name='teacher_classes',
            field=models.ManyToManyField(to='classes.class'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to='users.user'),
        ),
        migrations.AlterField(
            model_name='teacherdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_detail', to='users.user'),
        ),
    ]
