# Generated by Django 5.0.1 on 2024-06-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("ann_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "ann_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("teacher", "Teacher"),
                            ("all", "All"),
                            ("standard", "Standard"),
                            ("division", "Division"),
                            ("subject", "Subject"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "filter_content",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ann_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="announcements.announcement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("attach_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX")], max_length=10
                    ),
                ),
                ("file_path", models.TextField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "ann_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="announcements.announcement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="announcement",
            name="attachment",
            field=models.ManyToManyField(
                related_name="announcements", to="announcements.attachment"
            ),
        ),
    ]
