# Generated by Django 5.0.1 on 2024-06-14 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
        ("schools", "0002_alter_school_options_remove_school_principal_and_more"),
        ("users", "0002_alter_studentdetail_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcementscope",
            name="ann_id",
        ),
        migrations.AddField(
            model_name="announcement",
            name="ann_school_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.school",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="announcement",
            name="scope",
            field=models.ManyToManyField(
                related_name="announcements", to="announcements.announcementscope"
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="ann_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
    ]
