# Generated by Django 5.0.1 on 2024-06-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcementscope",
            name="filter_content",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="announcementscope",
            name="filter_type",
            field=models.CharField(
                choices=[
                    ("division", "Division"),
                    ("standard", "Standard"),
                    ("full_name", "Full Name"),
                    ("department", "Department"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
