# Generated by Django 5.0.1 on 2024-06-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_remove_announcementscope_ann_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="attachment",
            field=models.ManyToManyField(
                blank=True, related_name="announcements", to="announcements.attachment"
            ),
        ),
    ]
