# Generated by Django 5.0.6 on 2024-07-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcementscope_filter_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementscope',
            old_name='scope',
            new_name='scope_context',
        ),
        migrations.AlterField(
            model_name='announcementscope',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='announcements.announcement'),
        ),
        migrations.AlterField(
            model_name='announcementscope',
            name='filter_type',
            field=models.CharField(choices=[('standard_division', 'Standard & Division'), ('standard', 'Standard'), ('full_name', 'Full Name'), ('department', 'Department')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='announcements.announcement'),
        ),
    ]
