# Generated by Django 5.0.1 on 2024-06-14 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0003_alter_announcement_attachment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="ann_from",
            new_name="ann_author",
        ),
        migrations.RenameField(
            model_name="announcement",
            old_name="ann_id",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="ann_school_id",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="ann_id",
        ),
        migrations.AddField(
            model_name="announcement",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="announcements",
                to="announcements.attachment",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="announcementscope",
            name="ann_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="announcements.announcement",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="announcementscope",
            name="filter_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("division", "division"),
                    ("standard", "standard"),
                    ("subject_taught", "subject_taught"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcementscope",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("student", "student"),
                    ("teacher", "teacher"),
                    ("all", "all"),
                ],
                max_length=10,
            ),
        ),
    ]
